framework:
    default_locale: ru
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - ru
            - en
            - bg
            - de 
            - pt
        providers:
