vich_uploader:
    db_driver: orm

    mappings:
        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        paralax:
            uri_prefix: /images/paralax
            upload_destination: '%kernel.project_dir%/public/images/paralax'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        commercial:
            uri_prefix: /images/commercial
            upload_destination: '%kernel.project_dir%/public/images/commercial'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        slider:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        teachers:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        testimonial:
            uri_prefix: /images/testimonial
            upload_destination: '%kernel.project_dir%/public/images/testimonial'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
